# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(564, 236)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px\n"
"")
        Form.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.ImageButton = QtWidgets.QPushButton(parent=Form)
        self.ImageButton.setGeometry(QtCore.QRect(40, 30, 161, 161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImageButton.sizePolicy().hasHeightForWidth())
        self.ImageButton.setSizePolicy(sizePolicy)
        self.ImageButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ImageButton.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.ImageButton.setStyleSheet("border:none;")
        self.ImageButton.setText("")
        icon = QtGui.QIcon.fromTheme("application-x-executable")
        self.ImageButton.setIcon(icon)
        self.ImageButton.setIconSize(QtCore.QSize(160, 180))
        self.ImageButton.setCheckable(False)
        self.ImageButton.setAutoExclusive(False)
        self.ImageButton.setDefault(False)
        self.ImageButton.setObjectName("ImageButton")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(220, 10, 271, 111))
        self.label.setStyleSheet("border: none")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(210, 110, 331, 19))
        self.label_2.setStyleSheet("border:none")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:26pt; font-weight:700;\">@Czy_4201b</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "Github: https://github.com/SpeechlessMatt"))
