# Form implementation generated from reading ui file 'FuckDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 151, 71))
        self.label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label.setObjectName("label")
        self.Not0RetButton = QtWidgets.QPushButton(parent=Dialog)
        self.Not0RetButton.setGeometry(QtCore.QRect(20, 90, 151, 81))
        self.Not0RetButton.setObjectName("Not0RetButton")
        self.AnswerErrButton = QtWidgets.QPushButton(parent=Dialog)
        self.AnswerErrButton.setGeometry(QtCore.QRect(200, 90, 151, 81))
        self.AnswerErrButton.setObjectName("AnswerErrButton")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 190, 321, 61))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "测试点结果："))
        self.Not0RetButton.setText(_translate("Dialog", "非零返回"))
        self.AnswerErrButton.setText(_translate("Dialog", "答案错误"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700; text-decoration: underline; color:#aa0000;\">别关闭我，关了只能重新开始！！</span></p></body></html>"))
